10 варик

#32

Используя модуль array и библиотеку numpy, решить следующие задачи:
а) Дан массив  𝐴  размера  𝑁 . Сформировать новый массив B того же размера по следующему правилу: элемент BK равен сумме элементов массива  𝐴  с номерами от  𝐾  до  𝑁 .

In [6]:
import numpy as np

A = np.array([1,2,3,4,5])
B = np.zeros(len(A), dtype=int)

for i in range(len(A)):
    B[i] = sum(A[i:len(A)])

B

array([15, 14, 12,  9,  5])

б) Дана матрица размера 𝑀×𝑁 . Упорядочить ее строки так, чтобы их первые элементы образовывали возрастающую последовательность.

In [28]:
matr = np.array([
    [1,2,3,4],
    [4,3,2,1],
    [3,2,1,4]
])

sort_matr = matr[np.argsort(matr[:, 0])]
print(sort_matr)

[[1 2 3 4]
 [3 2 1 4]
 [4 3 2 1]]


#33

Дан стек. Необходимо проверить, является ли его содержимое последовательностью арифметической прогрессии.

In [8]:
class Stack:
    def __init__(self):
        self.items = []
    
    def is_empty(self):
        return len(self.items) == 0
    
    def push(self, item):
        self.items.append(item)
    
    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        else:
            raise IndexError("error")
    
    def size(self):
        return len(self.items)

In [9]:
def func(stack):
    if (stack.is_empty()):
        return False
    elif (stack.size() <= 2):
        return True
    else:
        el = stack.pop()
        el1 = stack.pop()
        d = el - el1
        while not stack.is_empty():
            el2 = stack.pop()
            if el1 - el2 != d:
                return False
            el1 = el2
        return True


stack = Stack()
stack.push(5)
stack.push(9)
stack.push(13)
stack.push(17)

print(func(stack))
        

True


#34

Создать класс очереди, который будет хранить только элементы определенного типа данных. Тип элементов задается при инициализации объекта класса очереди. При добавлении элемента, если его тип не соответствует заданному, то он не должен добавляться.

In [31]:
class Queue:
    def __init__(self, type):
        self.queue = []
        self.type = type

    def is_empty(self):
        return len(self.queue) == 0
    
    def push(self, item):
        if isinstance(item, self.type):
            self.queue.append(item)
        else:
            raise TypeError('error')

    def pop(self):
        if not self.is_empty():
            return self.queue.pop(0)
        else:
            raise IndexError('error')

    def size(self):
        return len(self.items)
    
    def __str__(self):
        return f"Queue({self.type.__name__}): {list(self.queue)}"
    
    def __repr__(self):
        return self.__str__()


In [35]:
queue = Queue(int)
queue.push(1)
queue.push(2)
#queue.push('3')
print(queue)

Queue(int): [1, 2]
